state = "https://nodes.dusk.network:8585"
prover = "https://provers.dusk.network:8686"
explorer = "https://explorer.dusk.network/transactions/transaction/?id="

[network.devnet]
state = "https://devnet.nodes.dusk.network:8585"
prover = "https://devnet.provers.dusk.network:8686"
explorer = "https://explorer.dusk.network/transactions/transaction/?id="

[network.local]
state = "http://127.0.0.1:8080"
prover = "http://127.0.0.1:8080"
